### ISSUE TITLE
Emporia EV Charger

### ISSUE THREAD

**Issue by Jakkumn** [flaviut/emporia-vue2-reversing#10]
While not the vue2, I suspect the ev charger is probably pretty similar and am planning on tinkering about with it. Was looking at the internals and was curious if anyone had seen on their vue2 labeling like as follows for tx/rx/vcc/gnd before I go and start trying to figure out what pin is what. I am hoping left to right is what it looks like in the vue2 (3.3,5,tx,rx,gnd,en,io0). Feel free to close immediately if this is too off topic.
![emporia_ev_charger](https://user-images.githubusercontent.com/1594342/180693783-ce2735fc-51d2-4ee9-8fb7-edea183cb65a.jpg)
.

**Comment by flaviut** [comment]
Someone else has brought up the ev charger at some point—but basically, the
software will be completely different and this code will not be helpful.

However, as far as determining the pinout goes, the ESP32 module's pinout
is public. Use a multimeter in continuity mode to figure out what's
connected to what.
