### ISSUE TITLE
Dual pole breaker driving a single kitchen outlet - how do I use both phases?

### ISSUE THREAD

**Issue by workingmanrob** [flaviut/emporia-vue2-reversing#7]
Hi and first of all thanks for all the work on this.

Love the results I am seeing so far... although it has revealed that I will need a more roomy breaker box to fit all these clamps.

I have an odd ball circuit in my kitchen that uses a dual pole breaker with phase A driving the top plug and phase B driving the bottom one.

So far I have not been able to figure out a way to get one clamp to read this outlet correctly.  My latest attempt was to remove the multiplier and clamp around both wires but only one plug reports any draw.  If I use the other plug I see my phase B total jump but the plug reports 0W.

Any tricks I can pull here or am I going to be forced to use 2 clamps?

Thanks again!!

**Comment by flaviut** [comment]
You have what is called a multi-wire branch circuit. You will need two clamps, since there are two circuits: top -> neutral, bottom -> neutral.

**Comment by workingmanrob** [comment]
Darn - well thanks for confirming.

Cheers :beers:

**Comment by flaviut** [comment]
sure, happy to help :)
